SETTINGS_FILE_NAME = "settings.ini"

SETTINGS_PROPERTY_NAME = "settings"
SETTINGS_INSTANCE_BASE_URL_PROPERT_NAME = "baseUrl"
SETTINGS_INSTANCE_LINK_PROPERTY_NAME = "link"
SETTINGS_INSTANCE_RAW_CHANNEL_USER_PROPERTY_NAME = "rawChannelUser"
SETTINGS_INSTANCE_RAW_CHANNEL_PROPERTY_NAME = "rawChannel"
SETTINGS_PROPERTY_NAME = "settings"
SETTINGS_LIMIT_PROPERTY_NAME = "l"
SETTINGS_DIRECT_PROPERTY_NAME = "d"
SETTINGS_COMMAND_PREFIX_PROPERTY_NAME = "prefix"

SETTINGS_CONTENT = {
  [SETTINGS_PROPERTY_NAME] = {
    [SETTINGS_COMMAND_PREFIX_PROPERTY_NAME] = "/rlu-",
    [SETTINGS_INSTANCE_BASE_URL_PROPERT_NAME] = "https://logs.ivr.fi",
    [SETTINGS_INSTANCE_LINK_PROPERTY_NAME] = "/?channel=%channel%&username=%username%",
    [SETTINGS_INSTANCE_RAW_CHANNEL_USER_PROPERTY_NAME] = "/channel/%channel%/user/%username%",
    [SETTINGS_INSTANCE_RAW_CHANNEL_PROPERTY_NAME] = "/channel/%channel%",
    [SETTINGS_LIMIT_PROPERTY_NAME] = 10,
    [SETTINGS_DIRECT_PROPERTY_NAME] = false,
  }
}
