name: Release

on:
  push:
    branches:
      - main

jobs:
  create_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run create_dist.sh
        run: |
          chmod +x ./create_dist.sh
          ./create_dist.sh

      - name: Run release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x ./release.sh
          ./release.sh

